name: Zombies
main: io.lama06.zombies.ZombiesPlugin
api-version: 1.20
version: 1.0.0
author: Lama06
website: https://github.com/Lama06/Zombies-Plugin/
commands:
  zombies:
    description: Command of the Zombies plugin
    permission: zombies
permissions:
  zombies:
    default: op
    description: Gives access to the Zombies Plugin's command